package utils;

public enum GeneroLibro {
	FANTASIA,CIENCIA_FICCION,MISTERIO,ROMANCE,FICCION_HISTORICA,
	POESIA,TERROR,NOVELA_GRAFICA,CLASICOS,TEATRO,FILOSOFIA,
	INFANTIL,NO_FICCION,MANGA,NOVELA_NEGRA;
}
