version: '3.1'

services:
  db:
    image: postgres:15
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5432:5432"
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    restart: always

  odoo:
    image: odoo:18
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./odoo_addons:/mnt/extra-addons
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: odoo@odoo.com
      PGADMIN_DEFAULT_PASSWORD: odoo
    ports:
      - "5050:80"
    restart: always

volumes:
  odoo_db_data:
  #odoo_addons: